### ISSUE TITLE
Empty states for My Sayings and Custom Categories

### ISSUE THREAD

**Issue by Uma-mv** [willowtreeapps/eyespeak-ios#253]
**As a vocable app user, I would like to see an empty state message when I have just added a category**

NOTE: As of 3/21/22 this is mostly implemented.  It is hidden via a feature flag therefore wont appear in the App store and Adhoc schemes.  There may be a need for some design updates, but when that is worked on as part of this ticket, we will need to remove the feature flag.

Acceptance Criteria
- After successfully adding a category, navigating to the category on the home screen display an empty state screen.
- After successfully adding a category, navigating to the detail view of that category in Settings would display an empty state screen.
- If there are no `My Sayings` an empty state screen will be displayed. 

Design on Home Screen:
https://www.figma.com/file/mNrwUygVhTmuWnKNHHkenR/Vocable-New?node-id=1%3A141
Design in Settings:
https://www.figma.com/file/mNrwUygVhTmuWnKNHHkenR/Vocable-New?node-id=1%3A1344

**Comment by rhsalas3** [comment]
@SashankPatel 
I just reviewed this ticket on the current build from the `develop` branch. The empty states need to be implemented, for iPad and iOS. The designs seem to be out of date because the "edit category" screen doesn't match what's actually in the app. Should we also make efforts to update the designs, as a form of continuous documentation? Maybe we can chat with the team about it as we move forward.

Otherwise, this ticket looks to be relevant and ready for development. I am removing the 'Needs design review' label and adding 'Ready to Select' to communicate this.

CC: @sgordon1024

**Comment by SashankPatel** [comment]
Verified on PR: #491 : See PR for test scenarios.
