### ISSUE TITLE
Custom Category: Adding a Phrase - Alert When Duplicating Existing Phrase

### ISSUE THREAD

**Issue by Ly-Kyli** [willowtreeapps/eyespeak-ios#484]
**Story:** As a user, I want to be notified when I am adding a custom phrase that matches a pre-existing phrase. This includes any of my other custom phrase.

**Acceptance Criteria:**
1. If a user adds a phrase that's already been added before, we should present an alert notifying them: "This phrase already exists. Continue to add the phrase?" with the option of "Continue" and "Cancel".

Design: 
Discussed in meeting but need to follow up with Steve

**Comment by rhsalas3** [comment]
@SashankPatel 

@CananArikan and I tested this issue's implementation on @jsmorgan42 's PR #530 

The alert is functional and matches designs, but some of the flows in which we expect to get the alert, or not, have some issues. We are going to mark this issue as "Test requesting changes" and [I have left a comment on the PR conversation thread](https://github.com/willowtreeapps/vocable-ios/pull/530#issuecomment-1087934328) to specify what the issues are that we're seeing.

This issue is related to #461

**Comment by rhsalas3** [comment]
This feature has been tested and verified to be working as expected.

The alert appears and behaves as expected and matches designs.
