### ISSUE TITLE
Listening Mode can be toggled on when device is unsupported

### ISSUE THREAD

**Issue by Clstroud** [willowtreeapps/eyespeak-ios#645]
**Describe the bug**

The debug menu and in-app settings both permit the user to enable Listening Mode when the device is configured for a non-English language. This should not be possible. 

**To Reproduce**
1. Set the device to a supported non-English language (e.g. German)
2. Open the debug menu
3. Attempt to enable the feature flag  

**Expected behavior**
Toggles for the feature should be OFF and disabled/grayed out so the user can't enable them.
In the settings UI there should be a footer with copy explaining the feature's requirements to indicate why the toggle is disabled.

**Actual behavior**
Currently the toggles behave as though everything is normal

**Device Information**
- Affects all supported devices/OS versions

**Comment by rhsalas3** [comment]
@jsmorgan42 @SashankPatel @moyerr @Clstroud 

Per a conversation in our standup on 05/18:
- the expected behavior may need to be that the feature is OFF altogether. In other words, we hide the 'Listen' category and 'Listening Mode' settings. 
     - This solves our issue of what happens for a user that installs the app fresh or updates from a version that did not already have listen mode. An issue tracked by ticket #672 
- In the case that a user has already enabled listening mode from a supported language, and then toggles their device to an unsupported language, we would still want to present the "device is not supported" message.

**Comment by rhsalas3** [comment]
Per conversation on 5/26/2022:

We will keep this implementation; merging the PR once it's been re-tested.

For the flow where a user has not yet granted permission to Listen Mode, we will show a new screen that shows both the "not supported" message and the "when listening mode is enabled" description. This will be implemented in #672

**Comment by rhsalas3** [comment]
Re-tested the PR branch and confirmed our expected behavior, given recent conversations about this feature.
